version: "3.8"

networks:
  traefik-proxy-network:
    external: true
    name: proxy-net
  backend:
    driver: bridge

services:
  node:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - traefik-proxy-network
      - backend
    expose:
      - 38327 # use a reverse proxy like Traefik
    ports:
      - 38327:4567
    environment:
      - DOMAIN
      - ENABLE_TLS
      - CERTRESOLVER
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-net"
      - "traefik.http.routers.community.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.community.tls=${ENABLE_TLS}"
      - "traefik.http.routers.community.tls.certresolver=${CERTRESOLVER}"

  db:
    image: postgres:13.1-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - backend
    volumes:
      - postgresql:/data/db
    ports:
      - 5432:5432

volumes:
  postgresql:
